export const amenitiesData = [
  {
    id: "spa",
    title: "Spa",
    heading: "Enjoy a Peaceful Retreat in the Residential SPA",
    description:
      "Escape to tranquility at our Residential SPA. Experience rejuvenating Jacuzzi space, and amenities designed to relax your mind and refresh your spirit. Your peaceful retreat awaits.",
    image: "/images/amenities/spa.jpg",
    features: [
      "Luxurious sauna with natural stone elements",
      "Rejuvenating jacuzzi with temperature control",
      "Relaxation lounge with ambient lighting",
      "Professional massage and treatment rooms",
      "Aromatherapy and essential oil diffusers",
    ],
    ctaText: "Schedule a Spa Tour",
    ctaLink: "/contact",
  },
  {
    id: "pool",
    title: "Pool",
    heading: "Dive into Luxury at Our Resort-Style Pool",
    description:
      "Our stunning pool area offers a perfect blend of relaxation and recreation. With crystal clear waters, comfortable lounging areas, and attentive service, it's your own private oasis in the heart of the city.",
    image: "/images/amenities/pool.jpg",
    features: [
      "Temperature-controlled swimming pool",
      "Separate children's wading pool",
      "Poolside cabanas and loungers",
      "Underwater lighting for evening swims",
      "Professional lifeguard during peak hours",
    ],
    ctaText: "Explore Pool Amenities",
    ctaLink: "/contact",
  },
  {
    id: "gym",
    title: "Gym",
    heading: "State-of-the-Art Fitness Center for Active Living",
    description:
      "Our comprehensive fitness center is equipped with the latest cardio and strength training equipment to support your wellness journey. With professional trainers available and spacious workout areas, achieving your fitness goals has never been more convenient.",
    image: "/images/amenities/gym.jpg",
    features: [
      "Premium cardio and strength training equipment",
      "Dedicated yoga and stretching area",
      "Personal training services available",
      "24/7 secure access for residents",
      "Regular fitness classes and wellness programs",
    ],
    ctaText: "View Fitness Programs",
    ctaLink: "/contact",
  },
  {
    id: "groceries",
    title: "Groceries",
    heading: "Convenient On-Site Grocery and Essentials",
    description:
      "Never worry about last-mpoolinute shopping trips again. Our on-site grocery store offers fresh produce, everyday essentials, and specialty items, ensuring that convenience is always at your doorstep.",
    image: "/images/amenities/grocery.jpg",
    features: [
      "Fresh produce delivered daily",
      "Essential household items",
      "Gourmet and specialty products",
      "Extended operating hours",
      "Home delivery service for residents",
    ],
    ctaText: "Learn About Grocery Services",
    ctaLink: "/contact",
  },
  {
    id: "management",
    title: "Management",
    heading: "Professional Property Management at Your Service",
    description:
      "Our dedicated management team ensures that your living experience is seamless and worry-free. From maintenance requests to community events, we're here to provide exceptional service and support.",
    image: "/images/amenities/pool.jpg",
    features: [
      "24/7 responsive management team",
      "Online portal for service requests",
      "Regular property maintenance and inspections",
      "Community event planning and coordination",
      "Concierge services for residents",
    ],
    ctaText: "Meet Our Management Team",
    ctaLink: "/contact",
  },
  {
    id: "lobby",
    title: "Lobby",
    heading: "Elegant Welcome in Our Designer Lobby",
    description:
      "Make a grand entrance every day through our beautifully designed lobby. With comfortable seating areas, attentive concierge service, and striking architectural elements, our lobby sets the tone for the luxury experience that awaits within.",
    image: "/images/amenities/lobby.jpg",
    features: [
      "24-hour concierge service",
      "Comfortable waiting areas",
      "Secure package receiving and storage",
      "Elegant design with premium finishes",
      "Climate-controlled environment",
    ],
    ctaText: "Experience Our Welcome",
    ctaLink: "/contact",
  },
  {
    id: "power",
    title: "Power",
    heading: "Uninterrupted Power Solutions for Modern Living",
    description:
      "Enjoy peace of mind with our reliable power systems. Our properties feature backup generators, sustainable energy options, and smart power management to ensure your comfort and convenience are never compromised.",
    image: "/images/amenities/power.jpg",
    features: [
      "Backup generator systems",
      "Solar power integration",
      "Smart energy management",
      "EV charging stations",
      "Energy-efficient appliances and systems",
    ],
    ctaText: "Discover Our Power Solutions",
    ctaLink: "/contact",
  },
  {
    id: "parking",
    title: "Parking",
    heading: "Secure and Convenient Parking Facilities",
    description:
      "Our thoughtfully designed parking facilities offer security, convenience, and ample space for residents and their guests. With 24/7 monitoring and easy access, parking worries become a thing of the past.",
    image: "/images/amenities/parking.jpg",
    features: [
      "Assigned resident parking spaces",
      "Visitor parking availability",
      "24/7 security monitoring",
      "Well-lit and ventilated areas",
      "Electric vehicle charging stations",
    ],
    ctaText: "View Parking Options",
    ctaLink: "/contact",
  },
  {
    id: "security",
    title: "Security",
    heading: "Comprehensive Security for Your Peace of Mind",
    description:
      "Your safety is our priority. Our multi-layered security systems include 24/7 monitoring, controlled access, and trained personnel to ensure that you and your loved ones can enjoy life with complete peace of mind.",
    image: "/images/amenities/security.jpg",
    features: [
      "24/7 security personnel",
      "Advanced surveillance systems",
      "Secure access control",
      "Intercom systems for visitor screening",
      "Emergency response protocols",
    ],
    ctaText: "Learn About Our Security Measures",
    ctaLink: "/contact",
  },
];
